n- name: Escaneo con Trivy
  uses: aquasecurity/trivy-action@master
  with:
    image-ref: devops-app
    format: table
    exit-code: 0

- name: Análisis con SonarQube
  uses: SonarSource/sonarqube-scan-action@v5
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}